Repository wave-harmonic/crest, pull requests merged in 2021-04, with the labels that each got.

#759 Toggles to flip flow map channels
  crest/Assets/Crest/Crest/Shaders/OceanInputs/FlowAddFlowMap.shader
Labels: enhancement

#803 Add version and RP to HelpURL
  crest/Assets/Crest/Crest/Scripts/Constants.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs
  crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFoam.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsWave.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
  crest/Assets/Crest/Crest/Scripts/Spline/Spline.cs
  crest/Assets/Crest/Crest/Scripts/WaterBody.cs
  docs/README.md
  docs/about/history.rst
Labels: enhancement

#805 Add "Known Issues" page
  docs/about/history.rst
  docs/about/known-issues.rst
  docs/conf.py
  docs/index.rst
Labels: Documentation

#806 Validate scene view effects options
  crest/Assets/Crest/Crest/Scripts/Crest.asmdef
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  docs/about/history.rst
Labels: enhancement

#804 Rewrite multi-property attributes as decorated/decorator attributes
  crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
  crest/Assets/Crest/Crest-Examples/Shared/Scripts/Collision/OceanSampleDisplacementDemo.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/EmbeddedFieldAttribute.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
  crest/Assets/Development/Editor/AttributeValidator.cs
  crest/Assets/Development/Editor/AttributeValidator.cs.meta
  crest/Assets/Development/Editor/Crest.Development.Editor.asmdef
  docs/about/history.rst
Labels: bug
