Repository wave-harmonic/crest, pull requests merged in 2021-09, with the labels that each got.

#876 Report renderer bounds by default for Animated Waves input
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
  docs/about/history.rst
Labels: enhancement

#901 Add dynamic waves depth cache reflections
  crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
  docs/about/history.rst
Labels: enhancement

#899 Clip surface input inverted option
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
  crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceConvexHull.shader
  crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceSignedDistance.shader
  docs/about/history.rst
Labels: enhancement

#902 Water body material override
  crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/WaterBody.cs
  docs/about/history.rst
  docs/user/water-bodies.rst
Labels: enhancement

#906 Fix underwater caustics jittering in XR when far from zero
  crest/Assets/Crest/Crest/Shaders/Helpers.meta
  crest/Assets/Crest/Crest/Shaders/Helpers/BIRP.meta
  crest/Assets/Crest/Crest/Shaders/Helpers/BIRP/Common.hlsl
  crest/Assets/Crest/Crest/Shaders/Helpers/BIRP/Common.hlsl.meta
  crest/Assets/Crest/Crest/Shaders/Helpers/BIRP/InputsDriven.hlsl
  crest/Assets/Crest/Crest/Shaders/Helpers/BIRP/InputsDriven.hlsl.meta
  crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterEffect.shader
  crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterMask.shader
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskHorizonShared.hlsl
  docs/about/history.rst
Labels: bug

#905 Fix white texture when sims are disabled with texture quality below full resolution (workaround)
  crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
  docs/about/history.rst
Labels: bug, unity bug

#909 Add ObsoleteShaderGUI
  crest/Assets/Crest/Crest/Scripts/Editor/ObsoleteShaderGUI.cs
  crest/Assets/Crest/Crest/Scripts/Editor/ObsoleteShaderGUI.cs.meta
Labels: enhancement

#913 Fix underwater high CPU memory usage
  crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
  crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterEffect.shader
  crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterMask.shader
  docs/about/history.rst
Labels: bug

#916 Fix default spectrum breaking in editor when enabled in play mode for ShapeFFT
  crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
  docs/about/history.rst
Labels: bug

#915 Fix FFTs not updating with spectrum changes when paused
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
  docs/about/history.rst
Labels: bug
