Repository wave-harmonic/crest, pull requests merged in 2021-12, with the labels that each got.

#949 Add Attenuation in Shallows setting to Dynamic Waves
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsWave.cs
  crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
  docs/about/history.rst
  docs/user/ocean-simulation.rst
Labels: enhancement

#947 Fix shadow bleeding at shorelines
  crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
  crest/Assets/Crest/Crest/Shaders/ShaderLibrary/UpdateShadow.hlsl
  docs/about/history.rst
Labels: bug

#948 Fix server builds and LodData* toggling
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  docs/about/history.rst
Labels: bug

#946 Optional maximum wave attenuation
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
  crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstner.shader
  crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerGeometry.shader
  docs/about/history.rst
  docs/user/ocean-simulation.rst
  docs/user/shallows-and-shorelines.rst
Labels: enhancement

#950 Fix floating origin for ShapeGerstner and ShapeFFT
  crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Shaders/OceanGlobals.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstner.shader
  crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerGeometry.shader
  docs/about/history.rst
Labels: bug

#954 Fix shadow simulation error recovery
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/SimSettingsShadow.cs
  docs/about/history.rst
Labels: bug, enhancement

#955 Add option for Ocean Renderer to ignore Water Body culling
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  docs/about/history.rst
Labels: enhancement

#956 Improve Water Body overlap when using Override Material
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  docs/about/history.rst
  docs/user/water-bodies.rst
Labels: enhancement

#952 Fix scale smoothing on height change on teleports
  crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  docs/about/history.rst
Labels: bug

#912 Water body auto clip-include
  crest/Assets/Crest/Crest/Scripts/WaterBody.cs
  crest/Assets/Crest/Crest/Scripts/WaterBody.cs.meta
  docs/about/history.rst
Labels: enhancement

#959 Fix underwater high memory
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
  docs/about/history.rst
Labels: bug

#960 Underwater from geometry
  crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
  crest/Assets/Crest/Crest/Shaders/Helpers/Resources.meta
  crest/Assets/Crest/Crest/Shaders/Helpers/Resources/Utility.shader
  crest/Assets/Crest/Crest/Shaders/Helpers/Resources/Utility.shader.meta
  crest/Assets/Crest/Crest/Shaders/Helpers/WaterVolume.hlsl
  crest/Assets/Crest/Crest/Shaders/Helpers/WaterVolume.hlsl.meta
  crest/Assets/Crest/Crest/Shaders/Ocean.shader
  crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
  crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterEffect.shader
  crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterMask.shader
  crest/Assets/Crest/Crest/Shaders/Underwater/Resources/WaterVolumeGeometry.shader
  crest/Assets/Crest/Crest/Shaders/Underwater/Resources/WaterVolumeGeometry.shader.meta
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffect.hlsl
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskHorizonShared.hlsl
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskShared.hlsl
  docs/about/history.rst
  docs/user/underwater.rst
Labels: enhancement

#966 Add TiledTexture shader struct
  crest/Assets/Crest/Crest/Shaders/Ocean.shader
  crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanNormalMapping.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanShaderData.hlsl
  crest/Assets/Crest/Crest/Shaders/ShaderLibrary/Common.hlsl
  crest/Assets/Crest/Crest/Shaders/ShaderLibrary/Common.hlsl.meta
  crest/Assets/Crest/Crest/Shaders/ShaderLibrary/Texture.hlsl
  crest/Assets/Crest/Crest/Shaders/ShaderLibrary/Texture.hlsl.meta
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffect.hlsl
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
Labels: Refactor

#965 Add more debug visualisers
  crest/Assets/Crest/Crest/Shaders/Ocean.shader
Labels: enhancement

#964 Add scrollbar to Ocean Debug GUI
  crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
  docs/about/history.rst
Labels: enhancement

#961 Allow any renderer as Ocean Input
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
  crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
  docs/about/history.rst
  docs/user/ocean-simulation.rst
Labels: enhancement
