Repository wave-harmonic/crest, pull requests merged in 2021-06, with the labels that each got.

#850 Fix InitBatches running every frame
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
  docs/about/history.rst
  docs/conf.py
Labels: bug

#853 Smooth wave rotation
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
  crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTSpectrum.compute
  docs/about/history.rst
Labels: enhancement

#299 Replace underwater effect with underwater post-processing shader
  crest/Assets/Crest/Crest-Examples/Main/Scenes/Internal/MainScene.prefab
  crest/Assets/Crest/Crest-Examples/Shared/Prefabs/DemoCamera.prefab
  crest/Assets/Crest/Crest-Examples/Shared/Prefabs/Internal/DemoCameraCore.prefab
  crest/Assets/Crest/Crest-Examples/Shared/Scripts/CamController.cs
  crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/PropertyWrapper.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/XRHelpers.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/XRHelpers.cs.meta
  crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/Underwater.meta
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs.meta
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs.meta
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs.meta
  crest/Assets/Crest/Crest/Shaders/Ocean.shader
  crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanFoam.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerBatch.shader
  crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepths.shader
  crest/Assets/Crest/Crest/Shaders/OceanLightingHelpers.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanLightingHelpers.hlsl.meta
  crest/Assets/Crest/Crest/Shaders/OceanSurfaceAlpha.shader
  crest/Assets/Crest/Crest/Shaders/Resources/OceanUnderwaterMask.shader
  crest/Assets/Crest/Crest/Shaders/Resources/OceanUnderwaterMask.shader.meta
  crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.compute
  crest/Assets/Crest/Crest/Shaders/Resources/UnderwaterEffect.shader
  crest/Assets/Crest/Crest/Shaders/Resources/UnderwaterEffect.shader.meta
  crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
  crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
  crest/Assets/Crest/Crest/Shaders/Resources/UpdateShadow.compute
  crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
  docs/user/rendering.rst
Labels: enhancement, in development

#855 Feature/share fft wave generators
  crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
  docs/about/history.rst
Labels: performance

#844 Overhaul of wave conditions section
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderBase.cs
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCustom.cs
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCutscene.cs
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderNetworked.cs
  docs/about/history.rst
  docs/conf.py
  docs/index.rst
  docs/user/other-features.rst
  docs/user/time-providers.rst
  docs/user/water-bodies.rst
  docs/user/wave-conditions.rst
Labels: Documentation
