Repository wave-harmonic/crest, pull requests merged in 2021-02, with the labels that each got.

#741 Convert inline SO editor to attribute
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/EmbeddedFieldAttribute.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/EmbeddedFieldAttribute.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/Editor/EmbeddedAssetHelpers.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/Editor/ScriptableObjectUtility.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Labels: enhancement

#749 Fix: always update cache components in editor
  crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
Labels: bug

#757 Fix broken RayTraceHelper
  crest/Assets/Crest/Crest/Scripts/Collision/RayTraceHelper.cs
Labels: bug

#760 Validate if ocean feature enabled, material keyword enabled
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
Labels: enhancement

#765 Fix ShapeGerstner breaking in build
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
Labels: bug

#764 Fix PSSL/PS4 shader errors
  crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
  crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
Labels: bug

#766 Add embedded material editor to OceanRenderer
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
Labels: enhancement

#768 Add inline button to fix validation issues
  crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
Labels: enhancement

#771 Add Crest icon to components and SOs under Crest/Scripts
  crest/Assets/Crest/Crest/Icons.meta
  crest/Assets/Crest/Crest/Icons/crest-oceanrender-logomark.png
  crest/Assets/Crest/Crest/Icons/crest-oceanrender-logomark.png.meta
  crest/Assets/Crest/Crest/Scripts/Collision/VisualiseCollisionArea.cs.meta
  crest/Assets/Crest/Crest/Scripts/Collision/VisualiseRayTrace.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/RenderAlphaOnSurface.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/RenderWireFrame.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs.meta
  crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs.meta
  crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs.meta
  crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteractionAdaptor.cs.meta
  crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs.meta
  crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsBase.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFlow.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFoam.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsWave.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/SimSettingsShadow.cs.meta
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs.meta
  crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs.meta
  crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs.meta
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs.meta
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs.meta
  crest/Assets/Crest/Crest/Scripts/Spline/Spline.cs.meta
  crest/Assets/Crest/Crest/Scripts/Spline/SplinePoint.cs.meta
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCustom.cs.meta
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderDefault.cs.meta
  crest/Assets/Crest/Crest/Scripts/WaterBody.cs.meta
Labels: ux
