Repository wave-harmonic/crest, pull requests merged in 2021-03, with the labels that each got.

#772 Add fix button for no renderer and for feature disabled
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
  crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
Labels: enhancement

#776 Fix PredicatedFieldAttribute not rendering
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/EmbeddedFieldAttribute.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
Labels: bug

#780 Add Crest icon to ScriptableObject classes
  crest/Assets/Crest/Crest/Icons.meta
  crest/Assets/Crest/Crest/Icons/crest-oceanrender-logomark.png
  crest/Assets/Crest/Crest/Icons/crest-oceanrender-logomark.png.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFlow.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFoam.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsWave.cs.meta
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/SimSettingsShadow.cs.meta
  crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs.meta
Labels: ux

#788 Change VFACE to SV_IsFrontFace
  crest/Assets/Crest/Crest/Shaders/Ocean.shader
Labels: bug

#789 Use AddComponentMenu for easier component searching
  crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
  crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/RippleGenerator.cs
  crest/Assets/Crest/Crest-Examples/Shared/Scripts/Collision/OceanSampleDisplacementDemo.cs
  crest/Assets/Crest/Crest-Examples/Shared/Scripts/Collision/OceanSampleHeightDemo.cs
  crest/Assets/Crest/Crest-Examples/Shared/Scripts/Collision/OceanSampleHeightEvents.cs
  crest/Assets/Crest/Crest-Examples/Shared/Scripts/UnderwaterEnvironmentalLighting.cs
  crest/Assets/Crest/Crest-Examples/Whirlpool/Scripts/Whirlpool.cs
  crest/Assets/Crest/Crest/Scripts/Collision/VisualiseCollisionArea.cs
  crest/Assets/Crest/Crest/Scripts/Collision/VisualiseRayTrace.cs
  crest/Assets/Crest/Crest/Scripts/Constants.cs
  crest/Assets/Crest/Crest/Scripts/Constants.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/RenderAlphaOnSurface.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/RenderWireFrame.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
  crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
  crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
  crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteractionAdaptor.cs
  crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
  crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
  crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
  crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
  crest/Assets/Crest/Crest/Scripts/Spline/Spline.cs
  crest/Assets/Crest/Crest/Scripts/Spline/SplinePoint.cs
  crest/Assets/Crest/Crest/Scripts/WaterBody.cs
Labels: enhancement

#767 Deprecate AssignLayer. Use LayerMask for depth cache
  README.md
  USERGUIDE.md
  crest/Assets/Crest/Crest-Examples/Main/Scenes/Internal/MainSceneCore.prefab
  crest/Assets/Crest/Crest/Scripts/Helpers/AssignLayer.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Editor/EditorHelpers.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Editor/WindowCrestWaterBody.cs
  crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/ProjectSettings/TagManager.asset
Labels: bug
