Repository wave-harmonic/crest, pull requests merged in 2021-05, with the labels that each got.

#813 Fix build errors for platforms without XR/VR support
  crest/Assets/Crest/Crest-Examples/Crest.Examples.asmdef
  crest/Assets/Crest/Crest-Examples/Shared/Scripts/CamController.cs
  crest/Assets/Crest/Crest/Scripts/Crest.asmdef
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
  docs/about/history.rst
Labels: bug

#814 Docs: Add sponsorship and roadmap
  docs/.gitignore
  docs/_static/custom.css
  docs/_static/custom.js
  docs/_templates/sidebar/brand.html
  docs/about/introduction.rst
  docs/about/roadmap.rst
  docs/conf.py
  docs/extensions/sponsor.py
  docs/extensions/trello.py
  docs/index.rst
  docs/user/collision-shape-for-physics.rst
  docs/user/includes/_birp-lighting.rst
  docs/user/includes/_birp-shadows.rst
  docs/user/includes/_urp-lighting.rst
  docs/user/other-features.rst
Labels: Documentation

#809 Gerstner upgrade - wind speed and wave pairs
  crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
  crest/Assets/Crest/Crest/Shaders/Resources/Gerstner.compute
Labels: enhancement

#827 Fix ocean tiles moving away from camera when far from zero
  crest/Assets/Crest/Crest/Shaders/Ocean.shader
  docs/about/history.rst
Labels: bug

#824 Fix null texture bindings
  crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
  crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
  docs/about/history.rst
Labels: bug

#828 Docs: add Rendering page. Improve lighting
  docs/about/history.rst
  docs/index.rst
  docs/user/configuration.rst
  docs/user/faq.rst
  docs/user/includes/_birp-reflections.rst
  docs/user/includes/_hdrp-reflections.rst
  docs/user/includes/_urp-reflections.rst
  docs/user/rendering.rst
  docs/user/technical-information.rst
  docs/user/underwater.rst
Labels: Documentation

#830 Fix "fix" helper exception and fix help box not showing
  crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
  docs/about/history.rst
Labels: bug

#815 Fix black "square" on Quest
  crest/Assets/Crest/Crest/Shaders/Ocean.shader
  crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
  crest/Assets/Crest/Crest/Shaders/OceanNormalMapping.hlsl
  docs/about/history.rst
Labels: bug

#816 Only show enabled spectrums in debug GUI
  crest/Assets/Crest/Crest/Scripts/Helpers/CrestSortedList.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Labels: bug

#637 Add XR SPI support to underwater post processing
  crest/Assets/Crest/Crest/Scripts/Helpers/XRHelpers.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/XRHelpers.cs.meta
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcess.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs
  crest/Assets/Crest/Crest/Shaders/Resources/OceanUnderwaterMask.shader
  crest/Assets/Crest/Crest/Shaders/Resources/UnderwaterPostProcess.shader
Labels: VR

#837 Fix bug where all ShapeGerstners used one wind heading
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  docs/about/history.rst
Labels: bug

#839 Make fields public for floaty things
  crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
  crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
  crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
  docs/about/history.rst
Labels: enhancement

#826 Use InputSystem when enabled in build settings
  crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
  crest/Assets/Crest/Crest-Examples/Crest.Examples.asmdef
  crest/Assets/Crest/Crest-Examples/Shared/Scripts/CamController.cs
  crest/Assets/Crest/Crest/Scripts/Crest.asmdef
  crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
Labels: enhancement
