Repository wave-harmonic/crest, pull requests merged in 2022-05, with the labels that each got.

#1012 Re-enable height queries in edit mode
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  docs/about/history.rst
Labels: enhancement

#1019 Fix jagged shoreline foam when using baked depth cache
  crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
  docs/about/history.rst
Labels: bug

#1017 Scale samples-per-wave with FFT res
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
  crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTSpectrum.compute
  docs/about/history.rst
Labels: enhancement

#1018 Fix memory/reference leaks
  crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  docs/about/history.rst
Labels: bug

#1022 Don't let flow period below 1s to avoid obvious phasing
  crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.compute
  crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.shader
  docs/about/history.rst
Labels: bug

#1033 Refactor HelpURL to be dynamic
  crest/Assets/Crest/Crest/Scripts/Constants.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/CrestHelpURLAttribute.cs
  crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/CrestHelpURLAttribute.cs.meta
  crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs
  crest/Assets/Crest/Crest/Scripts/Interaction/FloatingObjectBase.cs
  crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
  crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterAlbedoInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAlbedo.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsBase.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsClipSurface.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFlow.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFoam.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsSeaFloorDepth.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsWave.cs
  crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
  crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
  crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
  crest/Assets/Crest/Crest/Scripts/Spline/Spline.cs
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderBase.cs
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCustom.cs
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCutscene.cs
  crest/Assets/Crest/Crest/Scripts/Time/TimeProviderNetworked.cs
  crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
  crest/Assets/Crest/Crest/Scripts/WaterBody.cs
  docs/about/history.rst
  docs/user/ocean-simulation.rst
Labels: Refactor
